export const libraryCopy = {
  zh: {
    subtitle: '你与 Friday 完成的工作', sample: '示例文件', search: '搜索文件', source: '来源', category: '类型', all: '全部',
    categories: { document: '文档', spreadsheet: '表格', presentation: '演示', image: '图片', code: '代码', other: '其他' },
    clear: '清除筛选', more: '更多操作', download: '下载', rename: '重命名', remove: '删除', save: '保存', cancel: '取消',
    name: '文件名称', preview: '文件预览', close: '关闭预览', details: '来源与发送详情', originalDeleted: '原日程已删除', unavailable: '来源暂不可访问',
    empty: 'Friday 生成的文件会保存在这里', noResults: '没有找到符合条件的文件', loading: '正在加载文件…', loadFailed: '文件列表加载失败，请重试。', retry: '重试',
    renameFailed: '重命名失败，请检查名称后重试。', deleteFailed: '删除失败，文件已保留，请重试。', downloadFailed: '下载失败，请重试。',
    deleteTitle: '删除此文件？', deleteBody: '文件将从 Library 中移除，不会撤回已发送到群聊或个人的内容。',
    result: { 'not-sent': '未发送', sending: '发送中', sent: '已发送', partial: '部分发送失败', failed: '发送失败', unknown: '结果待确认' },
  },
  en: {
    subtitle: 'The work you and Friday have completed', sample: 'Sample files', search: 'Search files', source: 'Source', category: 'Type', all: 'All',
    categories: { document: 'Documents', spreadsheet: 'Spreadsheets', presentation: 'Presentations', image: 'Images', code: 'Code', other: 'Other' },
    clear: 'Clear filters', more: 'More actions', download: 'Download', rename: 'Rename', remove: 'Delete', save: 'Save', cancel: 'Cancel',
    name: 'File name', preview: 'File preview', close: 'Close preview', details: 'Source and delivery details', originalDeleted: 'Original routine deleted', unavailable: 'Source unavailable',
    empty: 'Files generated by Friday will appear here', noResults: 'No files match your filters', loading: 'Loading files…', loadFailed: 'Could not load your files. Please retry.', retry: 'Retry',
    renameFailed: 'Could not rename the file. Check the name and retry.', deleteFailed: 'Could not delete the file. It has been kept; please retry.', downloadFailed: 'Download failed. Please retry.',
    deleteTitle: 'Delete this file?', deleteBody: 'The file will be removed from Library. Files already sent to groups or people will not be recalled.',
    result: { 'not-sent': 'Not sent', sending: 'Sending', sent: 'Sent', partial: 'Some deliveries failed', failed: 'Delivery failed', unknown: 'Delivery unconfirmed' },
  },
}
